"""CardMarket public S3 catalog downloader.

Downloads the daily price guide + singles catalog for a given game ID.
No authentication required. Files are regenerated by CardMarket ~02:43 CET daily.

Usage:
    cat = CardmarketCatalog.download(game_id=GAME_ID_YGO)
    ids = cat.product_ids_for_name("Ash Blossom & Joyous Spring")
    prices = cat.prices_for_product(101788)  # {"avg7": 5.0, "avg30": 4.5, "avg1": 6.0}
"""
from __future__ import annotations

import logging
from dataclasses import dataclass, field

import httpx

logger = logging.getLogger(__name__)

GAME_ID_YGO = 3
GAME_ID_POKEMON = 6
GAME_ID_MTG = 1

_S3_BASE = "https://downloads.s3.cardmarket.com/productCatalog"
CM_SINGLES_CATALOG_URL = _S3_BASE + "/productList/products_singles_{game_id}.json"
CM_PRICE_GUIDE_URL = _S3_BASE + "/priceGuide/price_guide_{game_id}.json"

_TIMEOUT = 60.0  # seconds; files are 10-25 MB


@dataclass
class CardmarketCatalog:
    game_id: int
    created_at: str
    etag: str = ""
    _name_to_ids: dict[str, list[int]] = field(default_factory=dict, repr=False)
    _prices: dict[int, dict[str, float | None]] = field(default_factory=dict, repr=False)

    @classmethod
    def download(
        cls,
        *,
        game_id: int = GAME_ID_YGO,
        etag: str | None = None,
    ) -> "CardmarketCatalog | None":
        """Download catalog + price guide from CardMarket S3. No auth required.

        Pass etag (from a previous run's meta_json) to enable conditional fetch.
        Returns None on HTTP 304 Not Modified — caller should skip ingest entirely.
        """
        catalog_url = CM_SINGLES_CATALOG_URL.format(game_id=game_id)
        price_url = CM_PRICE_GUIDE_URL.format(game_id=game_id)

        # Condition the price guide fetch on ETag — it's the file that changes daily.
        # The catalog (product list) is always re-fetched to catch new cards added since last run.
        price_headers = {"If-None-Match": etag} if etag else {}

        logger.info("cardmarket_catalog_download game_id=%s etag=%s", game_id, etag or "none")

        price_resp = httpx.get(price_url, headers=price_headers, timeout=_TIMEOUT)
        if price_resp.status_code == 304:
            logger.info("cardmarket_price_guide_not_modified game_id=%s", game_id)
            return None
        price_resp.raise_for_status()
        price_data = price_resp.json()
        new_etag = price_resp.headers.get("ETag", "")

        catalog_resp = httpx.get(catalog_url, timeout=_TIMEOUT)
        catalog_resp.raise_for_status()
        catalog_data = catalog_resp.json()

        name_to_ids: dict[str, list[int]] = {}
        for product in catalog_data.get("products", []):
            name_key = product["name"].lower().strip()
            name_to_ids.setdefault(name_key, []).append(product["idProduct"])

        prices: dict[int, dict[str, float | None]] = {}
        for entry in price_data.get("priceGuides", []):
            pid = entry["idProduct"]
            prices[pid] = {
                "avg1":  entry.get("avg1"),
                "avg7":  entry.get("avg7"),
                "avg30": entry.get("avg30"),
            }

        logger.info(
            "cardmarket_catalog_loaded game_id=%s products=%s priced=%s etag=%s",
            game_id, len(name_to_ids), len(prices), new_etag,
        )
        return cls(
            game_id=game_id,
            created_at=catalog_data.get("createdAt", ""),
            etag=new_etag,
            _name_to_ids=name_to_ids,
            _prices=prices,
        )

    def product_ids_for_name(self, name: str) -> list[int]:
        """Return all CardMarket product IDs matching this card name (case-insensitive)."""
        return list(self._name_to_ids.get(name.lower().strip(), []))

    def prices_for_product(self, product_id: int) -> dict[str, float | None]:
        """Return {avg1, avg7, avg30} for a product ID. Returns all-None if unknown."""
        return self._prices.get(product_id, {"avg1": None, "avg7": None, "avg30": None})
